### ISSUE TITLE
Missing License file in npm package

### ISSUE THREAD

**Issue by char0n** [sindresorhus/capture-stack-trace#3]
Hello, is it possible to incorporate the LICENSE file inside the npm package ? Now it's missing. It's implied by MIT license that if licensed under the MIT the source code must be accompanied by full license text. If the license file is not in the npm package a lot of people cannot use it.

Thank you

**Comment by honzajavorek** [comment]
@floatdrop any chance you would get to this?

**Comment by floatdrop** [comment]
@honzajavorek published version `1.0.1` - now license should be in place.

**Comment by honzajavorek** [comment]
Thank you so much!
