### ISSUE TITLE
Yarn failed because the hash didn't match

### ISSUE THREAD

**Issue by LianJion** [sindresorhus/capture-stack-trace#5]
error: 
[1/4] Resolving packages...
[2/4] Fetching packages...
error http://registry.npm.taobao.org/capture-stack-trace/download/capture-stack-trace-1.0.1.tgz: Fetch succeeded for undefined. However, extracting "http://registry.npm.taobao.org/capture-stack-trace/download/capture-stack-trace-1.0.1.tgz" resulted in hash "a6c0bbe1f38f3aa0b92238ecb6ff42c344d4135d", which did not match the requested hash "ed0a1edb87c05d4db1037c5f8f483d8a3b5f0825".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

![snip20180918_129](https://user-images.githubusercontent.com/18100137/45667443-bc3f3380-bb4b-11e8-9d1c-1989ed931000.png)
Hello,  I found that the hash was changed but the version was not recently. So I should change the hash myself.

**Comment by Rpeanut** [comment]
+1

**Comment by neilzhengzx** [comment]
+1

**Comment by shenshanyoumu** [comment]
+1

**Comment by fenglu09** [comment]
+1

**Comment by fenglu09** [comment]
@LianJion  Have you solved it?

**Comment by sindresorhus** [comment]
This seems like an issue with that npm mirror, however, I have published a new patch release.
